services:
  - type: web
    name: knowledgemind-ai
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn --workers 1 --threads 2 --timeout 120 rag_agent.wsgi:application"
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
