# Generated by Django 6.0.6 on 2026-07-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_name', models.CharField(default='gpt-5', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
